version: "3"

services:
  db:
    build: containers/postgres
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres

  repl:
    build: .
    command: lein repl
    ports:
      - "3000:3000"
      - "39998:39998"
    depends_on:
      - db
    volumes:
      - ".:/duct-todo"
      - "lib_data:/root/.m2/repository"
    environment:
      - DEV_DB_URL=jdbc:postgresql://db:5432/todo-development?user=postgres&password=postgres
      - TEST_DB_URL=jdbc:postgresql://db:5432/todo-test?user=postgres&password=postgres
      - JWT_SECRET=FTy2ukHjI/uQfbj4j4ypr2Ua5xc4ctwM1eDv6RAeCh3Vms2Yzkh4jGrga9rigD9l

volumes:
  lib_data:
